'use client';

import { useState, useRef } from 'react';
import { motion, useInView, AnimatePresence } from 'framer-motion';
import Link from 'next/link';

function FadeUp({ children, delay = 0, className = '' }: { children: React.ReactNode; delay?: number; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const inView = useInView(ref, { once: true, margin: '-70px' });
  return (
    <motion.div ref={ref}
      initial={{ opacity: 0, y: 32 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1], delay }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

const FAQ_ITEMS = [
  {
    category: 'Getting Started',
    questions: [
      {
        q: 'Do I need to create an account to use ResuPulse?',
        a: "No. You can analyze your resume without any account or signup. Just upload your PDF and get your results instantly.",
      },
      {
        q: 'What file formats are supported?',
        a: "Currently we support PDF files up to 5MB. PDF is the standard for resumes and ensures consistent formatting when parsed by ATS systems.",
      },
      {
        q: 'How long does the analysis take?',
        a: "Most analyses complete in 20–40 seconds. We use Groq's ultra-fast AI inference to stream results in real time so you see progress as it happens.",
      },
    ],
  },
  {
    category: 'Analysis & Results',
    questions: [
      {
        q: 'How is the ATS score calculated?',
        a: "Our score evaluates keyword density, section completeness, formatting quality, quantified achievements, action verb usage, and contact information — the same criteria used by real ATS systems like Taleo, Workday, and Greenhouse.",
      },
      {
        q: 'What does the letter grade mean?',
        a: "A (90–100): Excellent ATS compatibility. B (75–89): Good, minor improvements needed. C (60–74): Fair, significant gaps exist. D (50–59): Poor, major revisions required. F (<50): Likely rejected by most ATS systems.",
      },
      {
        q: 'Are the keyword suggestions job-specific?',
        a: "The Free plan analyzes your resume for general industry keywords and common ATS patterns. The upcoming Pro plan will add job description matching, where you paste a specific job posting and get tailored keyword recommendations.",
      },
      {
        q: 'How accurate are the AI improvement suggestions?',
        a: "Our suggestions are generated by Llama 3.3 70B, one of the most capable open-source language models. They follow proven resume writing principles: quantified achievements, strong action verbs, and clear impact statements.",
      },
    ],
  },
  {
    category: 'Privacy & Security',
    questions: [
      {
        q: 'Is my resume data stored or shared?',
        a: "Your resume is processed in memory to generate the analysis. The analysis result (score, keywords, suggestions) is stored in your browser's analysis history. We never share your resume content with third parties.",
      },
      {
        q: 'Who can see my resume?',
        a: "Only you. We don't build user profiles, we don't associate resumes with identities, and we don't sell data. Your resume content is sent to our AI provider (Groq) solely for analysis and is not retained by them.",
      },
    ],
  },
  {
    category: 'Reports & History',
    questions: [
      {
        q: 'Can I download my analysis report?',
        a: "Yes. Every analysis includes a PDF export button that generates a professional report with your score, section breakdown, keyword analysis, and all improvement suggestions.",
      },
      {
        q: 'How many analyses can I save in history?',
        a: "The Free plan stores your 10 most recent analyses. You can view, compare, and re-download reports from your history page. The Pro plan (coming soon) offers unlimited history.",
      },
      {
        q: 'Can I re-analyze an updated resume?',
        a: "Absolutely — and we encourage it. Upload your revised resume after making improvements to see how your score has changed. Tracking progress is one of the most valuable ways to use ResuPulse.",
      },
    ],
  },
];

function AccordionItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="faq-item border-b border-gray-100 last:border-0 rounded-lg overflow-hidden">
      <button
        className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left"
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-gray-800 leading-snug">{question}</span>
        <motion.div
          animate={{ rotate: open ? 45 : 0 }}
          transition={{ duration: 0.25 }}
          className="shrink-0 w-6 h-6 rounded-full flex items-center justify-center"
          style={{ background: open ? 'linear-gradient(135deg, #7c3aed, #ec4899)' : '#f3f4f6' }}
        >
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke={open ? 'white' : '#6b7280'} strokeWidth="2.5">
            <line x1="12" y1="5" x2="12" y2="19" />
            <line x1="5" y1="12" x2="19" y2="12" />
          </svg>
        </motion.div>
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-4 text-sm text-gray-500 leading-relaxed">{answer}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FaqPage() {
  return (
    <div className="overflow-x-hidden">
      {/* Hero */}
      <section
        className="relative pt-32 pb-24 overflow-hidden"
        style={{ background: 'linear-gradient(150deg, #0b0614 0%, #16062a 60%, #0a0e1a 100%)' }}
      >
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute rounded-full opacity-30" style={{ width: 600, height: 600, background: 'radial-gradient(circle, rgba(124,58,237,0.5), transparent 70%)', top: -150, left: -100 }} />
          <div className="absolute rounded-full opacity-20" style={{ width: 400, height: 400, background: 'radial-gradient(circle, rgba(236,72,153,0.4), transparent 70%)', bottom: -80, right: -60 }} />
        </div>
        <div className="relative z-10 max-w-3xl mx-auto px-6 text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-purple-400/25 bg-purple-500/10 text-purple-300 text-sm font-medium mb-8">
              ❓ FAQ
            </div>
            <h1 className="text-5xl md:text-6xl font-extrabold text-white leading-[1.1] mb-6 tracking-tight">
              Frequently asked{' '}
              <span className="gradient-text">questions</span>
            </h1>
            <p className="text-lg text-gray-400 leading-relaxed">
              Everything you need to know about ResuPulse. Can't find what you're looking for? Reach out.
            </p>
          </motion.div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-24 pointer-events-none" style={{ background: 'linear-gradient(to top, #f9fafb, transparent)' }} />
      </section>

      {/* FAQ categories */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-3xl mx-auto px-6 space-y-12">
          {FAQ_ITEMS.map(({ category, questions }, ci) => (
            <FadeUp key={category} delay={ci * 0.1}>
              <div>
                <div className="flex items-center gap-3 mb-5">
                  <h2 className="text-lg font-bold text-gray-900">{category}</h2>
                  <span className="text-xs px-2.5 py-1 rounded-full bg-violet-100 text-violet-700 font-semibold border border-violet-200">
                    {questions.length}
                  </span>
                </div>
                <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden" style={{ boxShadow: 'var(--shadow-card)' }}>
                  {questions.map(({ q, a }) => (
                    <AccordionItem key={q} question={q} answer={a} />
                  ))}
                </div>
              </div>
            </FadeUp>
          ))}
        </div>
      </section>

      {/* Still have questions */}
      <section className="py-20 bg-white">
        <div className="max-w-2xl mx-auto px-6 text-center">
          <FadeUp>
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-violet-200 bg-violet-50 text-violet-700 text-sm font-medium mb-6">
              💬 Still have questions?
            </div>
            <h2 className="text-3xl font-bold text-gray-900 mb-4">We're here to help</h2>
            <p className="text-gray-500 mb-8 leading-relaxed">
              Can't find the answer you're looking for? Or just want to share feedback?
              Reach out and we'll get back to you quickly.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="mailto:support@resupulse.app"
                className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl font-semibold text-violet-700 border-2 border-violet-200 bg-violet-50 hover:bg-violet-100 transition-colors"
              >
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
                  <polyline points="22,6 12,13 2,6" />
                </svg>
                Email Support
              </a>
              <Link
                href="/analyze"
                className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-xl font-bold text-white transition-all hover:opacity-90"
                style={{ background: 'linear-gradient(135deg, #7c3aed, #ec4899)' }}
              >
                Try ResuPulse Free →
              </Link>
            </div>
          </FadeUp>
        </div>
      </section>
    </div>
  );
}


